/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-08-04 06:55:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validate(form){\r\n");
      out.write(" \tif(form.title.value ==\"\"){\r\n");
      out.write(" \t\talert(\"제목을 입력하세요.\"); return false;\r\n");
      out.write(" \t}\r\n");
      out.write(" \tif(form.nick.value == \"\"){\r\n");
      out.write(" \t\talert(\"닉네임을 입력하세요.\"); return false;\r\n");
      out.write(" \t}\r\n");
      out.write(" \tif(form.password.value==\"\"){\r\n");
      out.write(" \t\talert(\"암호를 입력하세요.\"); return false;\r\n");
      out.write(" \t}\r\n");
      out.write(" \tif(form.imagename.value==\"\"){\r\n");
      out.write(" \t\talert(\"이미지 파일을 선택하세요.\"); return false;\r\n");
      out.write(" \t}\r\n");
      out.write(" \tvar result = confirm(\"정말로 등록하시겠습니까?\");\r\n");
      out.write(" \tif(result == false) return false;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<form action=\"write.do\" method=\"post\" enctype=\"multipart/form-data\"\r\n");
      out.write("\tonSubmit=\"return validate(this)\">\r\n");
      out.write("\t<table border=\"1\" width=\"100%\">\r\n");
      out.write("\t\t<tr><td>글제목</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"title\" size=\"40\"/></td>\r\n");
      out.write("\t\t</tr>\t\r\n");
      out.write("\t\t<tr><td>닉네임</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"nick\" size=\"20\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr><td>이메일</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"email\" size=\"40\"/></td>\r\n");
      out.write("\t\t</tr>\t\r\n");
      out.write("\t\t<tr><td>암호</td>\r\n");
      out.write("\t\t<td><input type=\"password\" name=\"password\" size=\"20\"/></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr><td>이미지</td>\r\n");
      out.write("\t\t<td><input type=\"file\" name=\"imagename\" size=\"40\"/></td>\r\n");
      out.write("\t\t</tr>\t\r\n");
      out.write("\t\t<tr><td>글내용</td>\r\n");
      out.write("\t\t<td><textarea rows=\"8\" cols=\"40\" name=\"content\"></textarea></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"등 록\"/>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\t\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
