/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.79
 * Generated at: 2017-07-14 07:35:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class JSP_005fTest_005f02_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tlabel {\r\n");
      out.write("\twidth:160px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"JSP_Test_02.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form action=\"JSP_test_02\" method=\"get\" name=\"sign\">\r\n");
      out.write("\t\t<label>이름 : </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"name\"><br>\r\n");
      out.write("\t\t<label>주민 : </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"jumin\">-<input type=\"password\" name=\"jumin2\"><br>\r\n");
      out.write("\t\t<label>아디 : </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"id\"><br>\r\n");
      out.write("\t\t<label>비번 : </label>\r\n");
      out.write("\t\t<input type=\"password\" name=\"pw\"><br>\r\n");
      out.write("\t\t<label>비번확인 : </label>\r\n");
      out.write("\t\t<input type=\"password\" name=\"pw2\"><br>\r\n");
      out.write("\t\t<label>이메일 : </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"mail\">@<input type=\"text\" name=\"mail2\">\r\n");
      out.write("\t\t<select name=\"mail3\" size=\"1\">\r\n");
      out.write("\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t<option value=\"daum.net\">daum.net</option>\r\n");
      out.write("\t\t\t<option value=\"google.com\">google.com</option>\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label>우편번호: </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"post\"><br>\r\n");
      out.write("\t\t<label>주소 : </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"addr\">&nbsp;<input type=\"text\" name=\"addr2\"><br>\r\n");
      out.write("\t\t<label>폰번 : </label>\r\n");
      out.write("\t\t<input type=\"text\" name=\"phone\"><br>\r\n");
      out.write("\t\t<label>직업 : </label>\r\n");
      out.write("\t\t<select name=\"job\" size=\"3\">\r\n");
      out.write("\t\t\t<option value=\"\">선택</option>\r\n");
      out.write("\t\t\t<option value=\"학생\">학생</option>\r\n");
      out.write("\t\t\t<option value=\"군인\">군인</option>\r\n");
      out.write("\t\t\t<option value=\"언론\">언론</option>\r\n");
      out.write("\t\t\t<option value=\"공무원\">공무원</option>\r\n");
      out.write("\t\t\t<option value=\"유통업\">유통업</option>\r\n");
      out.write("\t\t\t<option value=\"제조업\">제조업</option>\r\n");
      out.write("\t\t\t<option value=\"운수업\">운수업</option>\r\n");
      out.write("\t\t\t<option value=\"개발자\">개발자</option>\r\n");
      out.write("\t\t\t<option value=\"자영업\">자영업</option>\r\n");
      out.write("\t\t</select><br>\r\n");
      out.write("\t\t<label>메일수신 : </label>\r\n");
      out.write("\t\t<input type=\"radio\" name=\"chk_mail\" value=\"ok\">수신\r\n");
      out.write("\t\t<input type=\"radio\" name=\"chk_mail\" value=\"no\">거부\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label>관심분야 : </label>\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"item\" value=\"신발\">신발\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"item\" value=\"원두\">원두\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"item\" value=\"창업\">창업\r\n");
      out.write("\t\t<input type=\"checkbox\" name=\"item\" value=\"헤어\">헤어\r\n");
      out.write("\t\t<br><hr>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"send\" onclick=\"return check()\">&nbsp;\r\n");
      out.write("\t\t<input type=\"reset\" value=\"cancle\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
